name: "Code Sign macOS Binary"
description: "Sign macOS binary"

inputs:
  platform:
    description: "Platform (darwin)"
    required: true
  target:
    description: "Target architecture (x64, arm64)"
    required: true

runs:
  using: composite
  steps:
    - name: Import macOS Developer Certificate
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ env.MACOS_CERTIFICATE }}
        p12-password: ${{ env.MACOS_CERTIFICATE_PWD }}

    - name: Sign macOS binary
      shell: bash
      env:
        MACOS_IDENTITY: ${{ env.MACOS_IDENTITY }}
      run: |
        # Sign the binary
        codesign --deep --force --options runtime -vvvv \
          --sign "$MACOS_IDENTITY" \
          --entitlements apps/cli/entitlements.plist \
          apps/cli/bin/untrace-${{ inputs.platform }}-${{ inputs.target }}

        # Verify code signing
        codesign -dvvv apps/cli/bin/untrace-${{ inputs.platform }}-${{ inputs.target }}