name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
    - uses: oven-sh/setup-bun@v2

    - shell: bash
      run: bun install
