name: "Python Setup"
description: "Setup Python environment and install dependencies for Python SDK"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Python package dependencies
      shell: bash
      working-directory: sdks/python
      run: |
        uv sync --dev
