name: "Update Monitoring Services"
description: "Create PostHog annotation for CLI release"

inputs:
  version:
    description: "Version number for the release"
    required: true
  posthog_host:
    description: "PostHog host URL"
    required: true
  posthog_api_key:
    description: "PostHog API key"
    required: true

runs:
  using: composite
  steps:
    - name: Create PostHog release annotation
      shell: bash
      run: |
        curl -X POST "https://${{ inputs.posthog_host }}/api/projects/@current/annotations/" \
        -H "Authorization: Bearer ${{ inputs.posthog_api_key }}" \
        -H "Content-Type: application/json" \
        -d '{
          "content": "CLI v${{ inputs.version }} released",
          "scope": "project",
          "date_marker": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
        }'