name: Elixir SDK Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Changeset NPM Release"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  packages: write
  actions: read

env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      is_version_bump: ${{ steps.check.outputs.is_version_bump }}
      elixir_version_changed: ${{ steps.check-elixir.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: check
        run: |
          if [[ "${{ github.event.workflow_run.head_commit.message }}" =~ ^chore:\ version\ packages.*$ ]]; then
            echo "is_version_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_version_bump=false" >> $GITHUB_OUTPUT
          fi

      - id: check-elixir
        name: Check if Elixir SDK version changed
        run: |
          # Check if the Elixir SDK version was bumped in mix.exs
          if git diff HEAD~1 HEAD -- sdks/elixir/mix.exs | grep -q 'version:'; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Elixir SDK version was changed in mix.exs"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Elixir SDK version was not changed in mix.exs"
          fi

  release:
    name: Release Elixir SDK
    needs: check-version
    runs-on: ubuntu-latest
    if: needs.check-version.outputs.is_version_bump == 'true' && needs.check-version.outputs.elixir_version_changed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          # Need full history for Changesets
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26'

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./sdks/elixir/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: sdks/elixir
        run: |
          mix deps.get
          mix deps.compile

      - name: Run tests
        working-directory: sdks/elixir
        run: |
          mix test

      - name: Build Elixir package
        working-directory: sdks/elixir
        run: |
          mix hex.build

      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          cd sdks/elixir
          mix hex.publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: elixir-sdk-v${{ steps.version.outputs.version }}
          name: Elixir SDK v${{ steps.version.outputs.version }}
          body: |
            Release of Elixir SDK v${{ steps.version.outputs.version }}

            This release includes:
            - Elixir SDK package published to Hex
            - Version: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
