name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'packages/**'
      - 'apps/**'
      - '.github/workflows/integration-tests.yml'

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # Skip this job for now
    if: false

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup database
        run: |
          bun run db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/test

      - name: Build packages
        run: bun run build --filter=@untrace/integ-test...

      - name: Run integration tests
        run: bun run test:ci
        working-directory: packages/integ-test
        env:
          CI: true
          USE_LOCAL_DB: true
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/test
          SUPABASE_URL: http://localhost:54321
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: packages/integ-test/test-results/
          retention-days: 7

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./packages/integ-test/coverage/lcov.info
          flags: integration
          name: integration-tests
          fail_ci_if_error: false

  test-containers:
    name: Test with Containers
    runs-on: ubuntu-latest
    timeout-minutes: 25
    # Skip this job for now
    if: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build --filter=@untrace/integ-test...

      - name: Run integration tests with containers
        run: bun run test:ci
        working-directory: packages/integ-test
        env:
          CI: true
          USE_LOCAL_DB: false
          # Test containers will automatically spin up PostgreSQL