name: Typecheck & Format

on:
  pull_request:
    branches: ["*"]
    paths:
      - "apps/**"
      - "packages/**"
      - "tooling/**"
      - "package.json"
      - "bun.lock"
      - "pnpm-lock.yaml"
  push:
    branches: ["main"]
    paths:
      - "apps/**"
      - "packages/**"
      - "tooling/**"
      - "package.json"
      - "bun.lock"
      - "pnpm-lock.yaml"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Format
        run: bun format:ci

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Typecheck
        run: bun typecheck:ci
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}